### ISSUE TITLE
Bundle .deb's location after install

### ISSUE THREAD

**Issue by cameronj86** [2e3s/awatcher#3]
I successfully installed awatcher (bundled .deb version) on my laptop running Wayland and got a few of the web-extension-related watchers up and running. So far so good.

I'd also like to install some additional watchers from GitHub as well, and their instructions (ie [step 3 here](https://github.com/RundownRhino/aw-watcher-mpv-sender)) are to place the downloaded watcher(s) in the same folder as aw-watcher-afk et al. 

I've been digging around my system for something that mirrors that aw-watcher-esque layout and can't seem to find anything. I know it's not $HOME/.config/awatcher as that is for the .toml files, so my question is where should manually installed watchers go? IE should be placed in /usr/bin/ along side awatcher, should I create a subfolder, or is this not a capability quite yet?

Thanks!

**Comment by 2e3s** [comment]
Hello! For now, you would need to run other watcher another way, like manually or with systemd. The original distribution manages to run watchers automatically with [an app for the tray icon](https://github.com/ActivityWatch/aw-qt) which config is suggested by the link, I didn't make such a functionality yet into the tray yet, although had some plans.
Instead, for the simplicity, what you need is to install the original distribution (`.deb` is [here](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.2)), then download `awatcher` as a watcher (not bundle), and run it with **aw-qt** as an extra watcher as suggested for [aw-watcher-mpv-sender](https://github.com/RundownRhino/aw-watcher-mpv-sender). Also turn off the original afk and window watchers since they are being replaced.

**Comment by 2e3s** [comment]
By the way, the watcher you mentioned might be covered by https://github.com/2e3s/aw-watcher-media-player if MPV supports MPRIS (almost all players do).
But that watcher won't be running automatically with awatcher-bundle, which of course I faced recently as well :smile: I've quickly made a rudimentary runner https://github.com/2e3s/awatcher/releases/tag/v0.2.2-beta1 but there is much more to do to catch up with **aw-qt**.

**Comment by cameronj86** [comment]
Thanks for the update and alternative solutions! I'm going to try and auto-start any additional watchers, and if that doesn't work, I'll pivot towards aw-qt + awatcher as my solution.
