### ISSUE TITLE
Does not support --testing flag and --port [number] is broken

### ISSUE THREAD

**Issue by brayo-pip** [2e3s/awatcher#34]
I get this error while running `aw-awatcher --port 5699`
```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.2/src/parser/error.rs:32:9:
Mismatch between definition and access of `port`. Could not downcast to TypeId { t: (14198805697026919078, 8142825056748903639) }, need to downcast to TypeId { t: (1403077013027291752, 4518903163082958039) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
`--testing` is not supported please consider supporting it. Just set port to 5699 if testing flag is passed. Will help with consistency across all major watchers. Will make the PR later but I might take too long.

**Comment by 2e3s** [comment]
Hello! Thanks for your report, fixed in https://github.com/2e3s/awatcher/commit/e2ee19f4940cb32d74c70d724cdc43b28d808d49

I will release it as v0.3.1 it nothing else pops up.

> `--testing` is not supported

It looks like an implicit alias to set a specific port (5666 as I could find), I suppose, so the explicit port option seems to cover it for now.

Other watchers are not aware of the testing port value btw, they use a provided flag https://github.com/ActivityWatch/aw-watcher-window/blob/c80aa5adbbe5959fcb661148aeb9f3898e6b68f3/aw_watcher_window/main.py#L63

**Comment by brayo-pip** [comment]
Thanks, I was not aware of that I assumed that `--testing` flag just sets it to the port 5666. :+1:
